# Generated by cucumber-sinatra. (2011-04-26 17:47:10 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'src/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Reforestanding

class ReforestandingWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ReforestandingWorld.new
end
